/* ### SPA 
- Được cho là cách tiếp cận hiện tại hơn
- Không yêu cầu tải lại trang trong quá trình sử dụng

### MPA
- Là cách tiếp cận cổ điển hơn
- Tải lại trang trong quá trình sử dụng ( Click vào đường link, )


## So sánh : 
### Tốc độ :
- SPA nhanh hơn khi sử dụng
     + Phần lớn tài nguyên được tải lần đầu
     + Trang chỉ tải dữ liệu mới khi cần
- MPA chậm hơn khi sử dụng
     + Luôn tải lại toàn bộ trang khi truy cập và chuyển hướng */